version: '3'
services:
  shop-nginx:
    build:
      context: ./docker
      dockerfile: nginx.docker
    volumes:
      - .:/app
    depends_on:
      - shop-php-fpm
    ports:
      - "80:80"
  shop-php-fpm:
    build:
      context: ./docker
      dockerfile: php-fpm.docker
    volumes:
      - .:/app
      - ./docker/php-fpm/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    tty: true
  shop-php-cli:
    build:
      context: ./docker
      dockerfile: php-cli.docker
    volumes:
      - .:/app
    tty: true
  shop-mysql:
    build:
      context: ./docker
      dockerfile: mysql.dockerFile
    environment:
      MYSQL_ROOT_PASSWORD: 111111
      MYSQL_DATABASE: shop
      MYSQL_USER: k0v4
      MYSQL_PASSWORD: 111111
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    tty: true
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    tty: true

  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.2
    ports:
      - "5601:5601"
    tty: true

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - shop-mysql:db
    ports:
      - 8744:80
    environment:
      MYSQL_ROOT_PASSWORD: 111111
      MYSQL_DATABASE: shop
      MYSQL_PASSWORD: 111111