version: '3'
services:
  shop-nginx:
    build:
      context: ./docker
      dockerfile: nginx.docker
    volumes:
      - .:/app
    depends_on:
      - shop-php-fpm
    ports:
      - "8083:80"
  shop-php-fpm:
    build:
      context: ./docker
      dockerfile: php-fpm.docker
    volumes:
      - .:/app
    tty: true
  shop-php-cli:
    build:
      context: ./docker
      dockerfile: php-cli.docker
    volumes:
      - .:/app
    tty: true
  shop-mysql:
    build:
      context: ./docker
      dockerfile: mysql.dockerFile
    environment:
      MYSQL_ROOT_PASSWORD: 111111
      MYSQL_DATABASE: shop
      MYSQL_USER: k0v4
      MYSQL_PASSWORD: 111111
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    tty: true